# Generated by Django 5.1.4 on 2026-04-17 07:18

import accounts.models
import accounts.validators
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0017_country_title_en_country_title_kk_country_title_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('photo', models.FileField(blank=True, null=True, upload_to=accounts.models.user_directory_path_ava, validators=[accounts.validators.validate_image_format], verbose_name='Фото профиля')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография')),
                ('experience', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание опыта')),
                ('post', models.CharField(blank=True, max_length=500, verbose_name='Должность')),
                ('linkedin', models.CharField(blank=True, max_length=500, verbose_name='LinkedIn')),
                ('role', models.CharField(choices=[('expert', 'Эксперт'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='expert', max_length=255, verbose_name='Роль')),
                ('status', models.CharField(choices=[('pending_email', 'Ожидает подтверждение E-mail'), ('pending_review', 'Ожидает подтверждения модератора'), ('active', 'Активный'), ('deactivated', 'Деактивированный')], default='pending_email', max_length=255, verbose_name='Статус')),
                ('deactivated_message', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.country', verbose_name='Страна')),
                ('expertises', models.ManyToManyField(to='content.expertise', verbose_name='Экспертизы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
