# Generated by Django 5.1.4 on 2026-04-15 18:38

import ckeditor_uploader.fields
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя переменной')),
                ('text_1', models.CharField(blank=True, max_length=500, verbose_name='Текст 1')),
                ('text_2', models.TextField(blank=True, verbose_name='Текст 2')),
                ('text_3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст 3')),
                ('icon', models.FileField(blank=True, upload_to=content.models.path_to_variables_icons, verbose_name='Иконка')),
                ('image', models.ImageField(blank=True, upload_to=content.models.path_to_variables_images, verbose_name='Картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=255, verbose_name='Имя переменной')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
                'ordering': ['order'],
            },
        ),
    ]
