# Generated by Django 5.1.4 on 2026-04-15 19:09

import ckeditor_uploader.fields
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('title_h1', models.CharField(max_length=500, verbose_name='Заголовок H1')),
                ('type', models.CharField(choices=[('text', 'Текстовая'), ('about', 'О компании'), ('services', 'Услуги'), ('sb', 'Steppe Brief'), ('researches', 'Исследования'), ('learning', 'Обучение'), ('contacts', 'Контакты'), ('register', 'Стать экспертом')], default='text', max_length=100, verbose_name='Шаблон страницы')),
                ('image', models.ImageField(blank=True, upload_to=content.models.path_to_pages_images, verbose_name='Картинка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('header_menu', models.BooleanField(default=False, verbose_name='Отображать в основном меню?')),
                ('footer_menu', models.BooleanField(default=False, verbose_name='Отображать в подвале?')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('order',),
            },
        ),
    ]
