# Generated by Django 5.1.4 on 2026-04-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_dedicated',
            field=models.BooleanField(default=False, verbose_name='Выделенный пункт?'),
        ),
    ]
