# Generated by Django 5.1.4 on 2026-04-15 20:33

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_page_is_dedicated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('type_1', 'Чем мы занимаемся'), ('type_2', 'Почему Steppe Intelligence'), ('type_3', 'О компании (Эксперты)'), ('type_4', 'Услуги'), ('type_5', 'Услуги (Steppe Brief)'), ('type_6', 'Что включено в каждый выпуск'), ('type_7', 'Для кого'), ('type_8', 'Кому подойдут наши программы'), ('type_9', 'Как проходит обучение'), ('type_10', 'Как начать?')], default='type_1', max_length=500, verbose_name='Тип карточки')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('icon', models.FileField(blank=True, upload_to=content.models.path_to_cards_icons, verbose_name='Иконка')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['order'],
            },
        ),
    ]
