# Generated by Django 5.1.4 on 2026-04-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='link',
        ),
    ]
