# Generated by Django 5.1.4 on 2026-04-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_card_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('type_1', 'Чем мы занимаемся'), ('type_2', 'Почему Steppe Intelligence'), ('type_3', 'О компании (Эксперты)'), ('type_4', 'Услуги (Steppe Brief)'), ('type_5', 'Что включено в каждый выпуск'), ('type_6', 'Для кого'), ('type_7', 'Кому подойдут наши программы'), ('type_8', 'Как проходит обучение'), ('type_9', 'Как начать?')], default='type_1', max_length=500, verbose_name='Тип карточки'),
        ),
    ]
