# Generated by Django 5.1.4 on 2026-04-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок'),
        ),
    ]
