# Generated by Django 5.1.4 on 2026-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_card_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема сообщения')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('phone', models.IntegerField(max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(max_length=500, verbose_name='E-mail')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('post', models.CharField(blank=True, max_length=500, verbose_name='Должность')),
                ('status', models.BooleanField(default=False, verbose_name='Обработанная?')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
