# Generated by Django 5.1.4 on 2026-04-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
