# Generated by Django 5.1.4 on 2026-04-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_application_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
    ]
