# Generated by Django 5.1.4 on 2026-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_application_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
