# Generated by Django 5.1.4 on 2026-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='plain',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на описание'),
        ),
    ]
