# Generated by Django 5.1.4 on 2026-04-16 11:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_plain_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='card',
            name='text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='card',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_kk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_h1_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_h1_kk',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_h1_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='plain',
            name='price_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='plain',
            name='price_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='plain',
            name='price_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='plain',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='plain',
            name='text_kk',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='plain',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='plain',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='plain',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='plain',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_1_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_1_kk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_1_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_2_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_3_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_3_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='variable',
            name='text_3_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='variable',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя переменной'),
        ),
        migrations.AddField(
            model_name='variable',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя переменной'),
        ),
        migrations.AddField(
            model_name='variable',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя переменной'),
        ),
    ]
