# Generated by Django 5.1.4 on 2026-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_card_text_en_card_text_kk_card_text_ru_card_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовая'), ('about', 'О компании'), ('services', 'Услуги'), ('sb', 'Steppe Brief'), ('researches', 'Исследования'), ('learning', 'Обучение'), ('contacts', 'Контакты'), ('register', 'Стать экспертом'), ('auth', 'Авторизация')], default='text', max_length=100, verbose_name='Шаблон страницы'),
        ),
    ]
