# Generated by Django 5.1.4 on 2026-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_country_title_en_country_title_kk_country_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Тип публикации',
                'verbose_name_plural': 'Тип публикаций',
            },
        ),
    ]
