# Generated by Django 5.1.4 on 2026-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_publicationtype_title_en_publicationtype_title_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный?'),
        ),
    ]
