# Generated by Django 5.1.4 on 2026-04-17 18:26

import ckeditor_uploader.fields
import content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_publicationtype_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('title_h1', models.CharField(max_length=500, verbose_name='Заголовок H1')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to=content.models.path_to_articles_images, verbose_name='Картинка')),
                ('short_text', models.TextField(verbose_name='Анонс')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('slug', models.SlugField(max_length=500, verbose_name='Slug')),
                ('by_subscription', models.BooleanField(default=False, verbose_name='По подписке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('countries', models.ManyToManyField(blank=True, to='content.country', verbose_name='Страна')),
                ('expertises', models.ManyToManyField(blank=True, to='content.expertise', verbose_name='Экспертизы')),
                ('types', models.ManyToManyField(blank=True, to='content.publicationtype', verbose_name='Тип публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-date',),
            },
        ),
    ]
