# Generated by Django 5.1.4 on 2026-04-17 18:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_en',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='article',
            name='date_kk',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='article',
            name='date_ru',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_text_en',
            field=models.TextField(null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_text_kk',
            field=models.TextField(null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_text_ru',
            field=models.TextField(null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_h1_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_h1_kk',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_h1_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок H1'),
        ),
    ]
