# Generated by Django 5.1.4 on 2026-04-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_article_date_en_article_date_kk_article_date_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_kk',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_ru',
        ),
    ]
