# Generated by Django 5.1.4 on 2026-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_remove_article_date_en_remove_article_date_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
