# Generated by Django 5.1.4 on 2026-04-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_article_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
