# Generated by Django 5.1.4 on 2026-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=123, max_length=500, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
