# Generated by Django 5.1.4 on 2026-04-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
