# Generated by Django 5.1.4 on 2026-04-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_article_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
