# Generated by Django 5.1.4 on 2026-06-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
